- components/GrantsAccordion.tsx
- components/ProjectDialog.tsx
- pages/project/[projectId]/grants.tsx
- pages/project/[projectId]/index.tsx
- pages/project/[projectId]/project.tsx
- utilities/getRPCByChainId.ts
- Changed mobile view of action buttons on project overview
- Changed grants selection to accordion
- Changed location of the grants tab section
> feat: mobile view

- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/GrantUpdate.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/Updates.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerificationsDialog.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerifiedBadge.tsx
- components/Pages/Project/Impact/AddImpactScreen.tsx
- components/Pages/Project/Impact/ImpactVerifications.tsx
- components/Pages/Project/Impact/VerifyImpactDialog.tsx
- components/Pages/Project/Impact/index.tsx
- package.json
- utilities/messages.ts
- yarn.lock
> feat: verify impact

- components/Searchbar/SearchList.tsx
- components/Searchbar/index.tsx
- components/Utilities/Header.tsx
- store/mobile.ts
> fix: mobile search

- components/Utilities/MarkdownEditor.tsx
https://app.asana.com/0/1201924619794704/1207237764242817/f
> Enable spellcheck in MarkdownEditor textarea

- utilities/chosenCommunities.ts
https://app.asana.com/0/1201924619794704/1207248890381800/f
> Add Climate Coordination to the list of communities in homep page

- pages/project/[projectId]/index.tsx
Added page not found routing to the projects which aren't available.
> Feat project not found

- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/ProgramRegistry/NetworkDropdown.tsx
https://app.asana.com/0/1201924619794704/1207337026032930/f
> feat: clean up add program

- components/CommunitiesDropdown.tsx
removed community without name in the community dropdown in grants tab
> Community dropdown- fix

- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/ProgramRegistry/ProgramDetailsDialog.tsx
- components/Pages/ProgramRegistry/ProgramList.tsx
- components/Pages/ProgramRegistry/ProgramListPending.tsx
> feat: changes to grant program registry

- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/ProgramRegistry/MyProgramList.tsx
- pages/funding-map/index.tsx
- pages/funding-map/manage-programs.tsx
- utilities/registry/checkIsPoolManager.ts
Pool manager is someone who can only manage their program.
> feat: pool manager

- components/Pages/Admin/AddAdminDialog.tsx
- components/Pages/Admin/CommunityAdmin.tsx
- components/Pages/Admin/RemoveAdminDialog.tsx
Need to add types properly, apart from that it's working.Kindly test it once again. I have tested with OP sepolia , it works ,and since we dont have endpoints in base sepolia , it doesnt work
> fixed admin listing

- components/Pages/ProgramRegistry/ManagePrograms.tsx
- utilities/indexer.ts
Project approval now fetch current manager list before create it.
> feat: fetching managers

- components/CommunityGrants.tsx
- components/Dialogs/GenerateImpactReportDialog.tsx
- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/ProgramRegistry/ProgramList.tsx
- components/Pages/ProgramRegistry/ProgramListPending.tsx
- components/Pages/Project/ProjectPage/ProjectBodyTabs.tsx
- components/Pages/Project/ProjectPage/index.tsx
- components/Utilities/Header.tsx
- package.json
- utilities/messages.ts
- yarn.lock
> feat: project updates

- app/[communityId]/admin/report-milestones/page.tsx
- components/Pages/Admin/ReportMilestonePage.tsx
- utilities/indexer.ts
> feat: adding grant titles filter

- components/Dialogs/ProjectDialog/NetworkDropdown.tsx
- components/Dialogs/ProjectDialog/index.tsx
> feat: adding project with chain selection

- components/Dialogs/CommunityDialog.tsx
- components/Dialogs/MergeProjectDialog.tsx
- components/Dialogs/ProjectDialog/index.tsx
- components/Dialogs/TransferOwnershipDialog.tsx
- components/Pages/Admin/AddAdminDialog.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/CompleteGrant.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/UpdateMilestone.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerifyGrantUpdateDialog.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerifyMilestoneUpdateDialog.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewGrant/index.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewGrantUpdate/index.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewMilestone/index.tsx
- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/ProgramRegistry/ManagePrograms.tsx
- components/Pages/Project/Impact/AddImpactScreen.tsx
- components/Pages/Project/Impact/EndorsementDialog.tsx
- components/Pages/Project/Impact/VerifyImpactDialog.tsx
- components/Pages/Project/ProjectPage/ProjectUpdateForm.tsx
- utilities/fetchData.ts
- utilities/sanitize.ts
> feat: sanitize inputs

- components/ContactInfoSubscription.tsx
- components/Pages/Project/ContactInfoPage.tsx
- store/project.ts
- Changed the contact tab in the project page according to the contact dialog in projectCreation .
- Added refreshContractInfo to the store
> feat: contact page

- app/admin/communities/stats/page.tsx
- components/Pages/Admin/CommunityStats.tsx
added community stats in separate page 
/admin/communities/stats
> feat : community stats

- components/Pages/Project/IntroDialog.tsx
- utilities/messages.ts
Added Contstaraints before calling the BE
> fix: Request Intro

- app/project/[projectId]/grants/[grantUid]/impact-criteria/page.tsx
- app/project/[projectId]/grants/[grantUid]/milestones-and-updates/page.tsx
- app/project/[projectId]/grants/[grantUid]/page.tsx
- app/project/[projectId]/grants/[grantUid]/review-this-grant/page.tsx
- app/project/[projectId]/grants/layout.tsx
- app/project/[projectId]/impact/page.tsx
- app/project/[projectId]/layout.tsx
- app/sitemaps/projects/sitemap.ts
- public/sitemap-0.xml
feat: SEO updates to include grants, milestones and impact + metadata changes for better visibility on search results
> feat: SEO updates + metadata changes 

- app/[communityId]/admin/milestones-report/page.tsx
- components/Pages/Admin/ReportMilestonePage.tsx
- Adding new column to Report milestones on Admins page: Output of work.
> feat: output on admin milestones

- app/project/[projectId]/roadmap/page.tsx
- components/Forms/ProjectObjectiveCompletion.tsx
- components/Pages/Project/Objective/Card.tsx
- components/Pages/Project/Objective/Completion.tsx
- components/Pages/Project/Objective/List.tsx
- components/Pages/Project/Objective/ObjectivesSub.tsx
- components/Pages/Project/Objective/SetAnObjective.tsx
> feat: roadmap new design

- components/ContactInfoSubscription.tsx
- components/Dialogs/CommunityDialog.tsx
- components/Dialogs/ProjectDialog/ContactInfoSection.tsx
- components/Dialogs/ProjectDialog/EditProjectDialog.tsx
- components/Dialogs/ProjectDialog/index.tsx
- components/Forms/GrantUpdate.tsx
- components/Forms/Milestone.tsx
- components/Forms/ProjectObjective.tsx
- components/Forms/ProjectUpdate.tsx
- components/Pages/Admin/RemoveAdminDialog.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewGrant/Milestone.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewGrant/index.tsx
- components/Pages/GrantMilestonesAndUpdates/screens/NewGrantUpdate/index.tsx
- components/Pages/ProgramRegistry/AddProgram.tsx
- components/Pages/Project/ProjectPage/ProjectUpdateForm.tsx
- components/Pages/Project/ProjectSubscription.tsx
- utilities/messages.ts
> feat: max 30 characters on titles

- components/Dialogs/ProjectDialog/EditProjectDialog.tsx
- components/Dialogs/ProjectDialog/index.tsx
- components/Dialogs/SimilarProjectsDialog.tsx
- store/modals/similarProjects.ts
Task: [Check for project name and alert creator if it already exists](https://app.asana.com/0/1201924619794704/1206158986373317/f)
> feat: similar projects

- app/projects/page.tsx
- components/Pages/Home/NewFeatureBanner.tsx
- components/Pages/Home/Presentation.tsx
- components/Pages/NewProjects/Loading.tsx
- components/Pages/NewProjects/ProjectCard.tsx
- components/Pages/NewProjects/index.tsx
- components/Pages/NewProjects/style.css
- types/project.ts
- utilities/indexer.ts
- utilities/pages.ts
> feat: new projects page

- app/[communityId]/projects-evaluator/loading.tsx
- app/[communityId]/projects-evaluator/page.tsx
- app/api/chat/route.ts
- components/Pages/Communities/CommunityProjectEvaluatorPage.tsx
- package.json
- tsconfig.json
- yarn.lock
- Added new dependencies: @ai-sdk/openai (v1.1.0) and ai (v4.1.0).
- Updated zod dependency to version 3.24.1.
- Changed TypeScript module resolution from 'node' to 'bundler'.
- Updated yarn.lock to reflect new and updated packages.
> feat: Add rag search for project evaluators

- components/Pages/Communities/CommunityProjectEvaluatorPage.tsx
- Enhanced the layout and styling of the Karma Co-pilot section for improved user experience.
- Adjusted the display of project evaluation capabilities with a more organized and visually appealing format.
- Added animation effects to the main container for a smoother user interface.
> refactor: Update UI for Community Project Evaluator Page

- app/api/chat/route.ts
- components/Pages/Communities/CommunityProjectEvaluatorPage.tsx
- package.json
- yarn.lock
- Updated AI SDK dependencies to latest versions (4.1.0 → 4.1.7)
- Refactored chat API route with improved error handling and async tool functions
- Added more comprehensive error management for external API calls
- Enhanced project data retrieval with better error logging and JSON parsing
- Improved chat component with tool invocation tracking and debugging
- Updated project card UI to display metric labels more clearly
> feat: Upgrade AI SDK and enhance chat API robustness, UI tweaks

- components/Dialogs/AdminTransferOwnershipDialog.tsx
- components/Pages/Project/ProjectNavigator.tsx
- components/Pages/Project/ProjectOptionsMenu.tsx
- hooks/useStaff.ts
- package-lock.json
- store/modals/adminTransferOwnership.ts
- utilities/enviromentVars.ts
- utilities/fetchData.test.tsx
- yarn.lock
- Introduced AdminTransferOwnershipDialog for transferring project ownership.
- Implemented state management for the dialog using Zustand.
- Updated ProjectOptionsMenu to include the new dialog for admin users.
- Enhanced fetchData utility to return additional error context.
- Adjusted environment variables for local development.
- Cleaned up unused imports and improved code organization in existing components.
> feat: add AdminTransferOwnershipDialog component and related store

- components/Forms/ProjectUpdate.tsx
- components/Pages/Communities/Impact/SearchWithValueDropdown.tsx
- components/Pages/Project/ProjectPage/ProjectBodyTabs.tsx
> feat: Edit project activity

- components/Dialogs/AdminTransferOwnershipDialog.tsx
- components/Pages/Project/ProjectOptionsMenu.tsx
- Removed unnecessary props and streamlined the component structure for clarity.
- Enhanced user feedback by updating success message to indicate potential delays.
- Consolidated account information retrieval in ProjectOptionsMenu for improved readability.
> refactor: simplify AdminTransferOwnershipDialog component

- components/Pages/Project/LinkDivviWalletButton.tsx
- components/Pages/Project/ProjectOptionsMenu.tsx
> feat: add divvi wallet

- components/Pages/Project/LinkDivviWalletButton.tsx
- components/Pages/Project/ProjectOptionsMenu.tsx
* feat: add divvi wallet
* feat: adding useCallback for link divvi wallet component
> feat: add divvi wallet (#469)

- components/Forms/ProjectUpdate.tsx
- components/Pages/Project/Impact/FilteredOutputsAndOutcomes.tsx
- components/Pages/Project/Impact/OutputsAndOutcomes.tsx
- components/Pages/Project/ProjectPage/ProjectActivityBlock.tsx
- hooks/index.ts
- hooks/useImpactAnswers.ts
- services/impactService.ts
* refactor: indicators data
* fix: solving conflict issue
> refactor: indicators data (#459)

- components/CommunityGrants.tsx
- components/Icons/ArrowIn.tsx
- components/Pages/Communities/Impact/ProgramFilter.tsx
- components/ProgramBanner.tsx
- services/programService.ts
- tailwind.config.js
- utilities/ReadMore.tsx
> feat: adding program banner

- app/project/[projectId]/layout.tsx
- components/Pages/Project/ProjectWrapper.tsx
* fix: redirect merged projects server-side
* fix: use slug lookup for pointer redirect
* feat: updating type
> Move pointer redirect to server (#499)

- components/Pages/Communities/CommunityPageNavigator.tsx
https://app.asana.com/1/1201924638493984/project/1201924619794704/task/1210499750187994?focus=true
> feat: Enhance CommunityPageNavigator to support optional programId in navigation paths

- components/Pages/Project/Loading/Overview.tsx
- components/Pages/Project/ProjectPage/ProjectImpact.tsx
- components/Pages/Project/ProjectPage/index.tsx
- hooks/useProjectImpactIndicators.ts
- utilities/indexer.ts
- Adds `useProjectImpactIndicators` hook to fetch data from newly created endpoint
- Shows new metrics of project impact on main project page - like Github Commits & Number of Transactions and Unique User transactions
> feat: adds information on summarized project dashboard metrics

- components/Searchbar/SearchList.tsx
- tailwind.config.js
* feat: enhancement on project/community search results
* chore: remove unused imports
* feat(search-list): re-orders projects and communities
* feat(search-list): uses ProfilePicture instead of Folder icon fallback
> feat: enhancement on project/community search results (#570)

- components/Pages/Admin/index.tsx
This PR refactors the community admin functionality to use **contract ownership** checks instead of **staff** checks, while expanding access control to show all communities to contract owners with appropriate permission restrictions.
- **Replaced `useStaff` hook with `useOwnerStore`**: Changed from staff-based permissions to contract owner-based permissions
- **Updated all conditional checks**: Changed `isStaff` references to `isOwner` throughout the component
- **Modified import statements**: Switched from `@/hooks/useStaff` to `@/store/owner`
- **Expanded community access for contract owners**: Modified filtering logic from `if (!isCommunityAdmin) return null;` to `if (!isCommunityAdmin && !isOwner) return null;`
- **Contract owners now see all communities**: Previously only communities …
> feat(community-admin): change staff for contract owner check

- .claude/settings.local.json
- components/FundingPlatform/ApplicationList/ApplicationList.tsx
- components/FundingPlatform/ApplicationList/ApplicationListWithAPI.tsx
- hooks/useFundingPlatform.ts
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1211356126940441
> Infinite scroll of applications

- app/community/[communityId]/admin/funding-platform/[programId]/question-builder/page.tsx
- components/ErrorBoundary/FormBuilderErrorBoundary.tsx
- components/QuestionBuilder/FieldEditor.tsx
- components/QuestionBuilder/FieldTypeSelector.tsx
- components/QuestionBuilder/QuestionBuilder.tsx
- hooks/useQuestionBuilder.ts
- public/sitemap-0.xml
- types/funding-platform.ts
Implements the admin interface for configuring post-approval forms as outlined in PRD v1.0 (Sept 15, 2025). This enables program administrators to create custom forms for collecting additional information from approved applicants.
- ✅ **Extended QuestionBuilder** component to support post-approval form configuration
- ✅ **Form schema management** with title, description, and custom fields
- ✅ **Real-time form preview** using existing form library components
- ✅ **Field validation** and error handling for form configuration
- ✅ **New post-approval section** in funding program setup flow
- ✅ **Toggle to enable/disable** post-approval form for each program
- ✅ **Form description field** that appears in both emails and grantee dashboard
- ✅ **Field management** using existing drag-and-drop …
> Feat: Post-Approval Form Configuration - Admin Frontend Implementation
